### ISSUE TITLE
No defualt HTML sanitization

### ISSUE THREAD

**Issue by ppotoplyak** [caitp/ui-comments#33]
Hi,

Thank you for lib, I am currently embedding into a project that I am working on.

Let me know if I am correct about no default sanitization taking place. i.e. the sanitization is left up to the user of ui-comments.  If so, can you recommend the best way to do sanitization?  I would use $sanitize but I don't think it supports the cyrillic alphabet.

thanks

**Comment by caitp** [comment]
I believe $sanitize does actually support cyrillic, which is all in the unicode basic multilingual plane. At some point support for supplemental codepoints was added too, but that isn't even needed for cyrillic.

Anyways, I don't totally remember the answer to your question, so I'll take a look and get back to you on that.

**Comment by ppotoplyak** [comment]
okay, thanks.

Is this a good place to ask you questions regarding ui-comments or would you rather receive questions via some other channel? or not receive questions at all :)

I am adding ui-comments to my project which uses the mean.js starter.  Currently, I am deciding on the best way to extend the back end in order to read and update comments which logically belong to an Article.  Do you happen to have any backend implementation examples or suggestions on the best way to model comments in the back end?

thanks, again

**Comment by caitp** [comment]
it's perfectly fine to ask questions here, go for it =)

**Comment by caitp** [comment]
Anyways, there's no "direct" api for $sanitizing comments --- the approach taken in the demo, is to just use a custom comment template which renders contents with `ng-bind-html`, which is implicitly sanitized. The api for sanitizing isn't really "built in", but PRs welcome

**Comment by ppotoplyak** [comment]
sorry, it turns out that I am not being very smart.   I though sanitization meant removing all html tags but it looks like some tags are deemed safe.  User error....
